# Generated by Django 3.1.2 on 2020-11-01 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_closedauctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedauctions',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
