# Generated by Django 3.1.2 on 2020-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201101_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Weapons'), ('2', 'Armor'), ('3', 'Bags'), ('4', 'Gems'), ('5', 'Consumables & Potions'), ('6', 'Trade Goods'), ('7', 'Magical Items')], max_length=30),
        ),
    ]
